# Generated by Django 4.1.7 on 2023-03-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='courses/media/default_course_image.jpg', upload_to='courses/%Y/%m/%d/'),
        ),
    ]
